spring.datasource.url=postgresql://neondb_owner:npg_a5qNBg9XmoYS@ep-weathered-cell-ayqqayax.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
