spring.application.name=ShopEase

# Server Port (Render or Local)
server.port=${PORT:9092}

# Fixed Dynamic Database URL (Added jdbc: prefix so both Render and Local will work smoothly)
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/shopease}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:reshma@hussain3009}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect