spring.application.name=ShopEase

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-weathered-cell-a4qqayax-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_a5qNBg9XmoYS
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Render-ku romba mukkiyam: PORT variable-ah eduthukira mari setup)
server.port=10000